// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/error_log.dart';
import 'data/raw_telemetry.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1560699920419585042),
    name: 'ErrorLog',
    lastPropertyId: const obx_int.IdUid(5, 2732616391134401151),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8887561030027245345),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7560091004574941318),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6924658878564717659),
        name: 'stackTrace',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7516561726254336373),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2732616391134401151),
        name: 'severity',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 3449348313109847874),
    name: 'RawTelemetry',
    lastPropertyId: const obx_int.IdUid(7, 2020706214565326325),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8706379523987368681),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8974460744584104313),
        name: 'accelX',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6472008641986417074),
        name: 'accelY',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6918108311010883618),
        name: 'accelZ',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1690093865516323115),
        name: 'magX',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 299813042225373938),
        name: 'magY',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2020706214565326325),
        name: 'magZ',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 3449348313109847874),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ErrorLog: obx_int.EntityDefinition<ErrorLog>(
      model: _entities[0],
      toOneRelations: (ErrorLog object) => [],
      toManyRelations: (ErrorLog object) => {},
      getId: (ErrorLog object) => object.id,
      setId: (ErrorLog object, int id) {
        object.id = id;
      },
      objectToFB: (ErrorLog object, fb.Builder fbb) {
        final messageOffset = fbb.writeString(object.message);
        final stackTraceOffset = fbb.writeString(object.stackTrace);
        final severityOffset = fbb.writeString(object.severity);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, messageOffset);
        fbb.addOffset(2, stackTraceOffset);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addOffset(4, severityOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final stackTraceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          isUtc: true,
        );
        final severityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final object = ErrorLog(
          message: messageParam,
          stackTrace: stackTraceParam,
          timestamp: timestampParam,
          severity: severityParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    RawTelemetry: obx_int.EntityDefinition<RawTelemetry>(
      model: _entities[1],
      toOneRelations: (RawTelemetry object) => [],
      toManyRelations: (RawTelemetry object) => {},
      getId: (RawTelemetry object) => object.id,
      setId: (RawTelemetry object, int id) {
        object.id = id;
      },
      objectToFB: (RawTelemetry object, fb.Builder fbb) {
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addFloat64(1, object.accelX);
        fbb.addFloat64(2, object.accelY);
        fbb.addFloat64(3, object.accelZ);
        fbb.addFloat64(4, object.magX);
        fbb.addFloat64(5, object.magY);
        fbb.addFloat64(6, object.magZ);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final accelXParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final accelYParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final accelZParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final magXParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final magYParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final magZParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final object = RawTelemetry(
          accelX: accelXParam,
          accelY: accelYParam,
          accelZ: accelZParam,
          magX: magXParam,
          magY: magYParam,
          magZ: magZParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ErrorLog] entity fields to define ObjectBox queries.
class ErrorLog_ {
  /// See [ErrorLog.id].
  static final id = obx.QueryIntegerProperty<ErrorLog>(
    _entities[0].properties[0],
  );

  /// See [ErrorLog.message].
  static final message = obx.QueryStringProperty<ErrorLog>(
    _entities[0].properties[1],
  );

  /// See [ErrorLog.stackTrace].
  static final stackTrace = obx.QueryStringProperty<ErrorLog>(
    _entities[0].properties[2],
  );

  /// See [ErrorLog.timestamp].
  static final timestamp = obx.QueryDateProperty<ErrorLog>(
    _entities[0].properties[3],
  );

  /// See [ErrorLog.severity].
  static final severity = obx.QueryStringProperty<ErrorLog>(
    _entities[0].properties[4],
  );
}

/// [RawTelemetry] entity fields to define ObjectBox queries.
class RawTelemetry_ {
  /// See [RawTelemetry.id].
  static final id = obx.QueryIntegerProperty<RawTelemetry>(
    _entities[1].properties[0],
  );

  /// See [RawTelemetry.accelX].
  static final accelX = obx.QueryDoubleProperty<RawTelemetry>(
    _entities[1].properties[1],
  );

  /// See [RawTelemetry.accelY].
  static final accelY = obx.QueryDoubleProperty<RawTelemetry>(
    _entities[1].properties[2],
  );

  /// See [RawTelemetry.accelZ].
  static final accelZ = obx.QueryDoubleProperty<RawTelemetry>(
    _entities[1].properties[3],
  );

  /// See [RawTelemetry.magX].
  static final magX = obx.QueryDoubleProperty<RawTelemetry>(
    _entities[1].properties[4],
  );

  /// See [RawTelemetry.magY].
  static final magY = obx.QueryDoubleProperty<RawTelemetry>(
    _entities[1].properties[5],
  );

  /// See [RawTelemetry.magZ].
  static final magZ = obx.QueryDoubleProperty<RawTelemetry>(
    _entities[1].properties[6],
  );
}
