name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # This makes builds faster by caching dependencies!

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Verify formatting
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      # Analyze the code
      - name: Analyze project source
        run: flutter analyze

      # Run tests
      - name: Run tests
        run: flutter test